In [1]:
import numpy as np

In [ ]:
# №1 Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# №2 Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# №3 Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули
a = np.diag(np.arange(1, 5), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# №4 Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.
a = np.random.random((5, 5))
an = a- a.mean(axis=1, keepdims=True)
print (an)

[[ 0.12101867  0.08903337 -0.16999962  0.06650909 -0.10656151]
 [-0.40725024  0.27887163  0.091879    0.10612615 -0.06962654]
 [-0.08983109  0.04333415  0.23928442 -0.47198905  0.27920157]
 [ 0.27945171  0.17996609 -0.00080694 -0.25180777 -0.20680308]
 [-0.10171942 -0.17508298 -0.39454852  0.56103098  0.11031994]]


In [ ]:
# №5 Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.
a = np.random.random((10, 3))
an = abs(a-0.5)
print(an)
result = an.min(axis = 1, keepdims = True)
print(result)

[[0.25698651 0.18400259 0.39148999]
 [0.22349418 0.17629451 0.49701735]
 [0.3527896  0.23445819 0.11309871]
 [0.28895083 0.22808597 0.43554428]
 [0.00970723 0.4880534  0.11621436]
 [0.17653721 0.44574861 0.08864527]
 [0.2334644  0.35004529 0.08903412]
 [0.153831   0.14707006 0.19953781]
 [0.47183672 0.47545906 0.10713381]
 [0.45658225 0.41355029 0.32510614]]
[[0.18400259]
 [0.17629451]
 [0.11309871]
 [0.22808597]
 [0.00970723]
 [0.08864527]
 [0.08903412]
 [0.14707006]
 [0.10713381]
 [0.32510614]]


In [ ]:
# №6 Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.
a = np.random.random((6, 6))
an = a.sum(axis=1, keepdims = True)/a.max(axis = 0, keepdims = True)
print(a)
print(np.diag(an))

[[0.90593549 0.32284647 0.84182099 0.89719248 0.26026117 0.43581119]
 [0.56750918 0.98819526 0.66770255 0.31332235 0.64475038 0.74659644]
 [0.22141667 0.11918875 0.26514482 0.15766865 0.27796449 0.84685361]
 [0.13962768 0.64404338 0.32604746 0.21049891 0.20995632 0.13678708]
 [0.67466218 0.96830506 0.88945691 0.29829746 0.68857878 0.45341677]
 [0.44930965 0.10546756 0.36790536 0.91523805 0.84985711 0.18211536]]
[4.04429214 3.975      2.12291002 1.82134128 4.67457069 3.38888926]


In [2]:
# №7 На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print (x[1:][zero[:-1]].max())

[False False  True False  True  True False False  True]
5


In [ ]:
# №8 Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i.
# В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
j = np.bincount(i)
k = np.append(j,np.zeros(len(x)-len(i)-1))
print(x+k)

[1. 1. 1. 1. 0. 3. 0. 0. 1. 0.]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
