In [3]:
import numpy as np

In [ ]:
# №1 Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# №2 Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# №3 Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули
a = np.zeros((5,5))
for i in range(1,5):
  a[i,i-1] = i
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [6]:
# №4 Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.
a = np.random.random((5, 5))
current_sum = 0
for i in range(0,5):
  for j in range(0,5):
    current_sum+=a[i,j]
  a[i] = a[i] - current_sum/5
  current_sum = 0
print (a)
#проверим, получатся очень маленькие числа, почти нули:
for i in range(0,5):
  for j in range(0,5):
    current_sum += a[i,j]
  print (current_sum)
  current_sum = 0

[[-0.01862251 -0.01850096 -0.13541419  0.06502284  0.10751481]
 [-0.03992856  0.15117842 -0.27946999  0.51436021 -0.34614007]
 [ 0.40364537  0.0804738   0.42740839 -0.50526535 -0.40626222]
 [-0.28252696  0.36070975 -0.43839818 -0.18252764  0.54274302]
 [ 0.22551907  0.07057006 -0.24857187 -0.19044616  0.14292891]]
4.440892098500626e-16
1.1102230246251565e-16
-1.1102230246251565e-16
0.0
2.7755575615628914e-16


In [ ]:
# №5 Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.
a = np.random.random((10, 3))
operation_result= []

for i in range(0,10):
  min_value = a[i,0]
  for j in range(0,3):
    if abs(a[i,j]-0.5) < abs(min_value-0.5):
      min_value = a[i,j]
  operation_result.append(min_value)
  min_value = 0.5
print(a)
print(operation_result)

[[0.88884592 0.89866651 0.87036971]
 [0.83161004 0.43491533 0.45735617]
 [0.7248648  0.22722514 0.77162084]
 [0.0082786  0.07568371 0.73102276]
 [0.60453514 0.80084725 0.77556091]
 [0.32480206 0.7376979  0.6870582 ]
 [0.79217467 0.87055257 0.32400863]
 [0.65226715 0.481569   0.68938606]
 [0.96223435 0.61546053 0.81139961]
 [0.49211679 0.10414998 0.43375724]]
[0.8703697064095712, 0.4573561674685219, 0.7248647988042333, 0.7310227615371575, 0.6045351374306374, 0.32480205991186606, 0.3240086297303051, 0.48156900313724715, 0.6154605347081226, 0.492116788601769]


In [ ]:
# №6 Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.
a = np.random.random((6, 6))
operation_result = []
resulting_sum = 0
max_value = 0;
for i in range (0,6):
  for j in range(0,6):
    if a[j,i]>max_value:
      max_value = a[j,i]
    resulting_sum+=a[i,j]
  operation_result.append(resulting_sum/max_value)
  max_value = 0
  resulting_sum = 0
print(a)
print(operation_result)


[[0.88441533 0.35925675 0.71147762 0.52603032 0.74816239 0.28517162]
 [0.29162277 0.19360144 0.32148533 0.18929065 0.24587587 0.94021518]
 [0.58761162 0.71644973 0.8272187  0.30052783 0.95835383 0.70679739]
 [0.10459892 0.84452874 0.54463191 0.09273277 0.49273982 0.28985458]
 [0.91801052 0.72973195 0.81515885 0.50616785 0.33701859 0.73305049]
 [0.01736274 0.34156837 0.69507775 0.38625122 0.60203837 0.48240672]]
[3.828402769993977, 2.583797494961895, 4.952691611217142, 4.503707539741642, 4.21466281609527, 2.6852418700013283]
2.3905573287889834
2.3905573361738726


In [ ]:
# №7 На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
maximum = False
for i in range(1, len(x)):
  if x[i - 1] != 0:
    continue
  if maximum == False:
    maximum = x[i]
  if x[i] > maximum:
    maximum = x[i]
print(maximum)


5


In [ ]:
# №8 Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i.
# В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(0, len(i)):
  x[i[j]]+=1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
